### ISSUE TITLE
System POSTs in safe mode

### ISSUE THREAD

**Issue by pablobfonseca** [pOH7/hackintosh-z390-h-9700k#1]
I'm using your config as I have the same MB and the same processor, but I'm getting the Safe mode screen when I reboot or turn on the computer. If I press F1 and quit the BIOS without saving it works fine, do you know what can be happening? 

Thanks!

**Comment by pablobfonseca** [comment]
Already solved

**Comment by pOH7** [comment]
@pablobfonseca Can you tell me how to solve the problem?
Currently, I disabled the "Wait For 'F1' If Error" boot configuration in BIOS.
Thanks!

**Comment by pablobfonseca** [comment]
@pOH7 I added some kexts and changed the config.plist, I'll share with you, this is the EFI folder:
[EFI.zip](https://github.com/pOH7/hackintosh-z390-h-9700k/files/4844939/EFI.zip)

**Comment by pOH7** [comment]
@pablobfonseca I fixed the problem by [DisableRtcChecksum](https://github.com/pOH7/hackintosh-z390-h-9700k/commit/ad4556a733e407f144b73a3c3155e110f5cab1b9)
